### ISSUE TITLE
How To Change Navigation Toggle?

### ISSUE THREAD

**Issue by foodin65** [MIGHTYminnow/trestle#14]
Hello, 

I'm curious how to change the navigation and header right toggles on mobile (default setup with the theme shows a menu icon and a search icon as toggles). 

Looks like this: http://cl.ly/image/2A1P0C2D3W2j

I would like to set it up to use the navigation button and have the header right show below the mobile logo, like in the theme demo, like this: http://cl.ly/image/3q1c3r1P0m2n

Thanks!

**Comment by BraadMartin** [comment]
Hello @foodin65,

We switched from using the mobile nav toggle style that you see in the demo to using the one you see now in version 2.0.0, and we haven't yet updated the demo site to the new version.

However, you can achieve the old style nav toggle with some extra CSS. First for the nav toggle button itself you could try something like this:

```
.nav-toggle {
    width: 100%;
    display: block;
    background-color: #444;
    margin-left: 0;
    font-size: 32px;
    text-align: center;
    color: #FFF;
    border-radius: 3px;
}
```

That will get the button itself looking more like the old style, but the label on the button will be "Toggle". You can change this directly in the theme-jquery.js file, or you can change it after the page loads with some jQuery like this:

````
$( '.toggle-button.targets-nav-primary' ).text( 'Navigation' );
````

Then for the Header Right Widget Area you might do something like this:

```
.toggle-button.targets-widget-area {
    display: none;
}

.site-header .widget-area {
    opacity: 1;
    position: relative;
    z-index: 0;
    box-shadow: none;
    border: none;
    background-color: #FFF;
}
```

That will get the widget area showing on screens less than 768px wide and hide the toggle button for the widget area, but the widget area will be below the nav. To fix that you can again use some jQuery:

```
$( '.header-widget-area' ).insertAfter( '.title-area' );
```

These are just some quick snippets that should help get you going, but of course matching the colors and font sizes and polishing things up to match your site's design will require additional CSS.

Hopefully this information helps you. I'm going to close this issue since there aren't any changes to make in the code, but feel free to reach out to us again if you have any more questions.
